### PR TITLE
Go Code suggestions

### PR DESCRIPTION
**Pull request by hoenn**
### :wave: Hello

I saw your project was using my HackerNews API bindings [go-hn](https://github.com/hoenn/go-hn) and wanted to contribute some changes back to improve the readability of the go code. This is not criticism of your code by any means and mostly represents [Effective Go](https://go.dev/doc/effective_go) suggestions.

I've tried to keep each commit specific to a few ideas, reading the commits individually will be a lot easier than scrolling through the entire PR. *Don't feel inclined to merge this PR for whatever reason*, I did this mostly for fun :slightly_smiling_face: 

#### Further suggestions
- It would be a good idea to take a stab at _removing_ all of the log.Print/Fatal and instead bubble errors back up through your application using `return fmt.Errorf("something went wrong: %w")` so that all of the context of an error will be wrapped up together when you log it higher up. [Blog post about error wrapping](https://golangbyexample.com/wrapping-and-unwrapping-error-golang/)
- Prefer having a small `main` function that kicks off the control flow for the application, right now there's a lot to read to get a picture of how the application works. 
- Function signatures like [`story *stories.Story, storyItem *hnapi.Story, commentItem *hnapi.Comment`](https://github.com/hoenn/hntoebook/blob/611b04ea3a9b3f0905adacf430e42715473f9563/stories/operations/pdf.go#L13) are usually a hint that you might want to write an `interface` to find the common denominator between the types you're passing around.
- Use a linter like [golangci-lint](https://github.com/golangci/golangci-lint) and make it easy to run locally and on the repository via GitHub actions or another CI platform if you'd like.
- A lot of the diff in this PR is related to reducing indentation. I see this project uses [badger](https://github.com/dgraph-io/badger), take a look through the source and you'll rarely see more than 2-3 indentations.
- Right now this code seems hard to write automated tests for (such as [UpdateStories](https://github.com/hoenn/hntoebook/blob/611b04ea3a9b3f0905adacf430e42715473f9563/stories/operations/update.go#L77
)). If you pass in a client rather than create one in that function you could more easily pass in a "fake" client that you could use to respond with bad data or just prefer to pass in all the data that function needs rather than have it do a lookup.

### CODE REVIEW

**Comment by abishekmuthian** [comment]
Awesome! Your library is a crucial component of this tool and I welcome this gesture 🙏 .

TBH this was a one day project where I scrapped together code from my service which sent HN items to Kindle via email and so didn't bother much about the quality of the code.

With your help of your PR and suggestions, I'll revisit the code.

**Comment by hoenn** [comment]
@abishekmuthian great to hear, let me know if I can help!

**Comment by hoenn** [comment]
Going to close this PR and delete my fork for the time being, but it could still be useful if you want to revisit the codebase.

**Comment by abishekmuthian** [comment]
Hey, Apologies for the delay. I was planning to review this over next weekend. I'm a [time-constrained person](https://abishekmuthian.com/time-constrained-person/) and so I wasn't able to prioritize this.

**Review by abishekmuthian — APPROVED** [review]

**Review by abishekmuthian — APPROVED** [review]

**Review by abishekmuthian — APPROVED** [review]

**Review by abishekmuthian — APPROVED** [review]

**Review by abishekmuthian — APPROVED** [review]

**Review by abishekmuthian — APPROVED** [review]

**Review by abishekmuthian — APPROVED** [review]

**Review by abishekmuthian — APPROVED** [review]

**Comment by abishekmuthian** [comment]
I've made a release v0.0.7 with these changes.

Once again, Thank you for taking the time to fix my laziness & carelessness; I also learnt few new tricks like using type assertions with your library and passing fake client to write test cases.

**Pull request merged**
